var1 = input('digite algo :')
print(type(var1))

print(var1.isalnum())
print(var1.isalpha())
print(var1.isdecimal())
print(var1.isascii())
print(var1.isdigit())
print(var1.isidentifier())
print(var1.islower())
print(var1.isnumeric())
print(var1.isprintable())
print(var1.isspace())
print(var1.istitle())
print(var1.isupper())
